### ISSUE TITLE
Recommended means of determining crash in prior execution

### ISSUE THREAD

**Issue by JakeSc** [uber/startup-reason-reporter#3]
It seems that this tool requires the input of whether the application crashed on a previous launch. I would have expected that to be output of the tool.

What is the recommended means of determining `previousRunDidCrash`? I see a couple proposed solutions here:
https://stackoverflow.com/questions/10885313/detect-app-crashed-during-load-last-time-it-was-run

Does Uber do something similar?

**Comment by artman** [comment]
Determining whether the application crashed is a pretty involved process and goes well beyond the scope of this tool.

Since all apps would (or should) come with a way to report crashes, we're providing an integration point in the startup-reason-reporter that can be fulfilled by whatever crash reporting tool the app uses. The most popular crash detection tool - Crashlytics - for example provides you with an API to determine whether the application crashed in the previous run.

**Comment by JakeSc** [comment]
Gotcha, thanks for the explanation @artman.

**Comment by thatjuan** [comment]
@artman given the introduction of UBApplicationStartupReasonReporterPriorRunInfo, does the answer to this question change? 

Is `UBApplicationStartupReasonReporterPriorRunInfo` meant to provide information about whether the application crashed during its previous execution, or is that still beyond the scope of this lib?
